### ISSUE TITLE
Error by running app.py

### ISSUE THREAD

**Issue by 00aixxia00** [Gotham13121997/FB-TO-TG-GROUP-CONNECT#1]
I'm getting the following message by running app.py

Traceback (most recent call last):
  File "/usr/lib/python3.7/configparser.py", line 788, in get
    value = d[option]
  File "/usr/lib/python3.7/collections/__init__.py", line 914, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.7/collections/__init__.py", line 906, in __missing__
    raise KeyError(key)
KeyError: 'admin_chat_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 46, in <module>
    adminlist=str(config.get('telegram','admin_chat_id')).split(',')
  File "/usr/lib/python3.7/configparser.py", line 791, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'admin_chat_id' in section: 'telegram'

Would be very happy if somebody can help me :)

**Comment by cB-Abhinav-Gautam** [comment]
Hello there. I am sorry about this issue. I have added this section in config.ini. IT is the chat id of the admin which was missing. You can get your chat id from https://t.me/getidsbot . This will notify you if your facebook token is expiring so you can renew it. Thanks for pointing it out

**Comment by 00aixxia00** [comment]
Thanks a lot. Just got the message "Your facebook user access token might have expired". Do i have to renew my facebook token now?

**Comment by cB-Abhinav-Gautam** [comment]
you can extend the access token. search about it online

**Comment by 00aixxia00** [comment]
yes found it , thank you a lot :)
